/// Store bootstrap: configuration, native library loading, the single
/// [Store] for the process, and the optional Sync client.
///
/// Contract (docs/contract/objectbox-capabilities.md §1): exactly one store
/// per process, opened once, centralized here. Everything else receives the
/// [Store] via constructor injection.
library;

import 'dart:ffi';
import 'dart:io';

import 'package:path/path.dart' as p;

import '../objectbox.g.dart'; // generated by build_runner
import 'model.dart';

/// Logs a line to stderr. stdout is reserved for the MCP JSON-RPC protocol,
/// so ALL diagnostics in this project go through stderr sinks like this one.
typedef LogSink = void Function(String message);

void stderrLog(String message) => stderr.writeln(message);

/// Matches C0 control characters (0x00-0x1F, 0x7F) — includes newlines,
/// carriage returns, and the ESC byte that starts ANSI escape sequences.
final RegExp _controlChars = RegExp('[\x00-\x1F\x7F]');

/// SEC-5 (2026-07-07 security review), moved here 2026-09-07 (L-6, security
/// review) so it can be shared by both [MemoryService] (which still exposes
/// it as `MemoryService.sanitizeForLog`, delegating to this function — see
/// that class for its own call sites) and [OllamaEmbedder] (embedder.dart),
/// which did not have access to it before and was interpolating raw Ollama
/// response bodies into log lines unsanitized. Strips C0 control characters
/// (newlines, ESC, etc.) from a value before it goes into a LOG line — a
/// value containing a newline or an ANSI escape sequence can forge log
/// lines or inject terminal escapes into the operator's stderr. Purely a
/// logging-hygiene guard: NEVER apply this to what gets STORED or returned
/// to a caller, only to what is written to a [LogSink].
String sanitizeForLog(String value) => value.replaceAll(_controlChars, '');

/// M-4 residual (2026-09-07 security-review re-verification), moved here
/// from `memory_service.dart`'s private `_truncateForError` so
/// `server.dart` can share it too (repo rule: no duplicated logic —
/// `MemoryService._truncateForError` was private to that library file and
/// therefore invisible outside it; see that class for its own delegating
/// wrapper and call sites). Truncates a value before it goes into an
/// error MESSAGE (as opposed to [sanitizeForLog], which strips control
/// characters for LOG lines) — an oversized, caller-controlled value
/// echoed verbatim into a `ValidationException` blows up the error
/// message itself (observed: a 1 MiB `expiresAt` produced a
/// 1,048,654-byte error message). Independent of any separate
/// length-rejection cap on the argument (e.g. `_requireLen` in
/// `memory_service.dart`) — this bounds what gets reflected back, even
/// for arguments that have no dedicated cap of their own.
String truncateForError(String value) =>
    value.length <= 120 ? value : '${value.substring(0, 120)}…';

/// How the process holds its ObjectBox [Store]. See lib/src/store_gate.dart
/// (the 2026-09-01 store-gate engineering log (internal), plan §1.1).
enum StoreMode {
  /// Today's behavior: one Store opened once at startup, held for the
  /// process lifetime. Default — do not change (WP7, out of scope for the
  /// Store-Gate feature itself).
  persistent,

  /// Store opened per request ([StoreGate.withStore]), guarded by an
  /// exclusive cross-process lock on `store.lock`. Lets many short-lived
  /// stdio processes (one per Claude Code session) safely share one store
  /// directory WITHOUT a serve-mode daemon. Mutually exclusive with
  /// `--serve` by design (see the `serveMode && storeMode == gated` check in
  /// bin/remembox.dart's `main()`), and with a non-empty [MemoryConfig.
  /// syncUrl] (checked below) — see the 2026-09-01 store-gate engineering
  /// log (internal), F5/plan §1.2.
  gated;

  static StoreMode fromEnvironment(String? raw) {
    switch ((raw ?? 'persistent').trim().toLowerCase()) {
      case 'persistent':
      case '':
        return StoreMode.persistent;
      case 'gated':
        return StoreMode.gated;
      default:
        throw ArgumentError(
          'OBX_MEMORY_STORE_MODE must be "persistent" or "gated", got '
          '"$raw".',
        );
    }
  }
}

/// Runtime configuration, sourced from environment variables with defaults.
class MemoryConfig {
  /// Directory holding the ObjectBox store.
  final String storeDir;

  /// Ollama embedding model id.
  final String embedModel;

  /// Base URL of the Ollama HTTP API.
  final String ollamaUrl;

  /// Expected embedding dimensionality. Must equal
  /// [MemoryIndex.hnswDimensions] (the schema-level HNSW dimensions) —
  /// checked at startup with a hard error, because a mismatch would corrupt
  /// retrieval quality silently otherwise.
  final int dims;

  /// Optional ObjectBox Sync server URL (e.g. ws://127.0.0.1:9997).
  /// Empty => no sync client is created at all (contract §9: "do not create
  /// a sync client when sync is disabled").
  final String syncUrl;

  /// Shared secret for sync auth; empty with [syncUrl] set => unauthenticated
  /// (localhost/trial trust model).
  final String syncCredentials;

  /// Ranking boost weights — see [MemoryConfig.describeRanking].
  final double rankWeightRecency;
  final double rankWeightFrequency;

  /// Whether a missing Ollama model may be pulled automatically at startup.
  final bool autoPull;

  /// Soft cap on `remember()`'s input text length, in characters (SEC-6,
  /// 2026-07-07 security review). Enforced by [MemoryService.remember] as
  /// an explicit [ValidationException] naming the limit and the actual
  /// size — never a silent truncation (project-wide no-silent-truncation
  /// rule, contract §8).
  final int maxTextChars;

  /// Whether this process should refuse to start if another RememBox
  /// process already holds a lock on [storeDir] (R2-6 follow-up, the
  /// 2026-07-06 engineering log (internal)'s 2026-07-07 "R2-6 Follow-up"
  /// section). Gates [StoreInstanceGuard]'s exclusive mode. Default
  /// `false`: a second
  /// process is tolerated (shared lock, warned via write-tool results), the
  /// documented pre-existing behavior. Set `true` on the process that
  /// should be the sole writer.
  final bool exclusive;

  /// How this process holds its [Store] — see [StoreMode]. Default
  /// `persistent` (unchanged behavior). Set via `OBX_MEMORY_STORE_MODE`.
  final StoreMode storeMode;

  MemoryConfig({
    required this.storeDir,
    required this.embedModel,
    required this.ollamaUrl,
    required this.dims,
    required this.syncUrl,
    required this.syncCredentials,
    required this.rankWeightRecency,
    required this.rankWeightFrequency,
    required this.autoPull,
    required this.maxTextChars,
    required this.exclusive,
    required this.storeMode,
  }) {
    // 2026-09-01, the 2026-09-01 store-gate engineering log (internal),
    // (plan §1.2): gated mode opens/closes the store per request — a live
    // ObjectBox Sync
    // connection needs a persistent store handle to stay connected, so
    // pairing the two would mean sync is constantly torn down and
    // reconnected, or silently misses server-pushed changes between
    // requests. Fail loud at construction time, the earliest point, not on
    // first use (mirrors the dims/maxTextChars validation style already in
    // this constructor's factory below).
    if (storeMode == StoreMode.gated && syncUrl.isNotEmpty) {
      throw ArgumentError(
        'OBX_MEMORY_STORE_MODE=gated is incompatible with '
        'OBX_MEMORY_SYNC_URL ("$syncUrl" is set). Gated mode opens/closes '
        'the store per request; a live ObjectBox Sync connection needs a '
        'persistent store handle to stay connected — sync would be '
        'constantly torn down and reconnected, or silently miss '
        'server-pushed changes between requests. Either unset '
        'OBX_MEMORY_SYNC_URL (gated mode still activates local writes via '
        'the existing reserved-port trick, same as persistent mode\'s '
        'local-only path) or use the default OBX_MEMORY_STORE_MODE='
        'persistent.',
      );
    }
    // 2026-09-01, the 2026-09-01 store-gate engineering log (internal),
    // (plan §14 MINOR): gated mode is self-defeating combined with
    // OBX_MEMORY_EXCLUSIVE=true —
    // a second gated process would die against instances.lock with a
    // message about the WRONG lock (instances.lock, not store.lock),
    // confusing the operator about what actually blocked it. Reject with an
    // actionable message, consistent with the syncUrl check above.
    if (storeMode == StoreMode.gated && exclusive) {
      throw ArgumentError(
        'OBX_MEMORY_STORE_MODE=gated is incompatible with '
        'OBX_MEMORY_EXCLUSIVE=true. Gated mode\'s whole point is letting '
        'multiple processes safely share one store directory '
        '(store.lock-serialized, per request); OBX_MEMORY_EXCLUSIVE refuses '
        'ANY second process outright (instances.lock), which would make a '
        'second gated process fail with a confusing instances.lock error '
        'instead of the store.lock behavior gated mode is meant to provide. '
        'Unset OBX_MEMORY_EXCLUSIVE for gated mode.',
      );
    }
  }

  factory MemoryConfig.fromEnvironment({Map<String, String>? env}) {
    final e = env ?? Platform.environment;
    // 2026-09-07, CLAUDE.md platform gotcha 3 / the 2026-09-02 store-gate
    // status note (internal): a rebuilt dist/ orphans a gated server's cwd
    // (rm -rf'd
    // inode). If HOME is also unset, the old `Directory.current.path`
    // fallback threw an opaque native PathNotFoundException instead of a
    // message naming what actually failed. Give an actionable ArgumentError
    // instead; when HOME IS set (the normal case) cwd is never consulted,
    // so behavior there is unchanged.
    final String home;
    if (e['HOME'] != null) {
      home = e['HOME']!;
    } else {
      try {
        home = Directory.current.path;
      } on FileSystemException catch (err) {
        throw ArgumentError(
          'Cannot determine a store directory: HOME is unset and the '
          'current working directory is gone (${err.message}). Set HOME or '
          'OBX_MEMORY_DIR, or run from a directory that still exists.',
        );
      }
    }
    final dimsRaw = e['OBX_MEMORY_DIMS'] ?? '768';
    final dims = int.tryParse(dimsRaw);
    if (dims == null || dims <= 0) {
      throw ArgumentError(
        'OBX_MEMORY_DIMS must be a positive integer, got "$dimsRaw"',
      );
    }
    double weight(String name, double def) {
      final raw = e[name];
      if (raw == null || raw.isEmpty) return def;
      final v = double.tryParse(raw);
      if (v == null || v < 0) {
        throw ArgumentError('$name must be a non-negative number, got "$raw"');
      }
      return v;
    }

    final maxTextCharsRaw = e['OBX_MEMORY_MAX_TEXT_CHARS'] ?? '32000';
    final maxTextChars = int.tryParse(maxTextCharsRaw);
    if (maxTextChars == null || maxTextChars <= 0) {
      throw ArgumentError(
        'OBX_MEMORY_MAX_TEXT_CHARS must be a positive integer, got '
        '"$maxTextCharsRaw"',
      );
    }

    // Deliberately the INVERSE idiom from OBX_MEMORY_AUTO_PULL's
    // permissive-true default: this flag defaults FALSE and only a literal
    // "true"/"1" (case-insensitive) flips it on. A typo landing on "on" for
    // a mode that REFUSES other instances to start would be far worse than
    // a typo landing on "off", so unlike autoPull's "anything but false
    // stays true", exclusive requires an explicit opt-in spelling.
    final exclusiveRaw = (e['OBX_MEMORY_EXCLUSIVE'] ?? '').toLowerCase();
    final exclusive = exclusiveRaw == 'true' || exclusiveRaw == '1';

    final storeMode = StoreMode.fromEnvironment(e['OBX_MEMORY_STORE_MODE']);

    return MemoryConfig(
      storeDir: e['OBX_MEMORY_DIR'] ?? p.join(home, '.remembox'),
      embedModel: e['OBX_MEMORY_EMBED_MODEL'] ?? 'embeddinggemma',
      ollamaUrl: e['OBX_MEMORY_OLLAMA_URL'] ?? 'http://localhost:11434',
      dims: dims,
      syncUrl: e['OBX_MEMORY_SYNC_URL'] ?? '',
      syncCredentials: e['OBX_MEMORY_SYNC_CREDENTIALS'] ?? '',
      rankWeightRecency: weight('OBX_MEMORY_RANK_W_RECENCY', 0.1),
      rankWeightFrequency: weight('OBX_MEMORY_RANK_W_FREQUENCY', 0.05),
      autoPull: (e['OBX_MEMORY_AUTO_PULL'] ?? 'true').toLowerCase() != 'false',
      maxTextChars: maxTextChars,
      exclusive: exclusive,
      storeMode: storeMode,
    );
  }

  /// Human-readable description of the recall ranking formula, logged once
  /// at startup so operators always know the active weights.
  String describeRanking() =>
      'score = similarity + $rankWeightRecency * exp(-ageDays/30) '
      '+ $rankWeightFrequency * min(accessCount,10)/10 '
      '(similarity = 1 - cosineDistance/2; v0 heuristic, tune via '
      'OBX_MEMORY_RANK_W_RECENCY / OBX_MEMORY_RANK_W_FREQUENCY)';
}

/// SEC (M-2, 2026-09-07 security review): dart:io has no chmod, so every
/// file/directory this project creates gets the process umask's permissions
/// by default — typically 0755 for directories and 0644 for files, i.e.
/// world-readable. `<storeDir>` holds the user's entire memory corpus
/// (`data.mdb`) plus the advisory `store.lock`/`instances.lock` files, none
/// of which any other local user should be able to read. Shared by
/// [openMemoryStore] (directory + `data.mdb`/`lock.mdb`), store_gate.dart's
/// `_openLockFile` (directory + `store.lock`) and instance_guard.dart's
/// `acquire` (directory + `instances.lock`) — each calls this right after
/// IT creates the path in question, so whichever of the three call sites
/// happens to be first (they race at process startup, see bin/remembox.dart)
/// is the one that actually runs `chmod`; the other two find the path
/// already existing and skip their own creation branch entirely, so this
/// never runs more than once per path in practice.
///
/// [mode] is a fixed literal chosen by the CALLER (never a tool argument or
/// other untrusted input) and [path] is always a path this code itself just
/// derived (store directory / a fixed filename under it) — never anything
/// supplied by an MCP tool call. POSIX only: skipped on Windows (logged,
/// not silently skipped) since Windows has no chmod-shaped permission model
/// here. Never throws — a permissions-tightening step failing must not turn
/// into a startup crash (contract §8's no-silent-failure rule cuts the
/// other way here: this WARNs loudly on failure rather than either
/// crashing OR silently leaving the looser default permissions in place).
void tightenPermissions(
  String path,
  String mode, {
  LogSink log = stderrLog,
}) {
  if (Platform.isWindows) {
    log(
      '[perms] skipping chmod $mode on $path (Windows has no POSIX chmod; '
      'this store directory is only permission-hardened on POSIX platforms)',
    );
    return;
  }
  final result = Process.runSync('chmod', [mode, path]);
  if (result.exitCode != 0) {
    log(
      '[perms] WARN: chmod $mode $path failed (exit ${result.exitCode}): '
      '${result.stderr.toString().trim()} — this path may still have the '
      'looser process-umask permissions it was created with',
    );
    return;
  }
  log('[perms] set $path to $mode');
}

/// M-2 upgrade-path follow-up (2026-09-07 security-review
/// re-verification): [tightenPermissions] above only ever ran when THIS
/// call created [path] (`isFirstOpen`/`!dir.existsSync()` guards in
/// [openMemoryStore]) — a store directory/file that already existed with
/// loose permissions from BEFORE this project started chmod'ing on
/// creation (a pre-M-2 build, upgraded in place) was left untouched,
/// silently, forever. An earlier design note claimed existence-checking
/// still caught that case; it does not (alternatives considered and
/// rejected are recorded in the internal engineering log).
///
/// Fix: cheaply `stat` [path] (`FileStat.statSync`, no subprocess) and
/// call [tightenPermissions] ONLY when the current mode is looser than
/// [expectedOctal] — i.e. any group/other permission bit is set. Called
/// from [openMemoryStore] on EVERY open, not just the creating one, so an
/// upgraded install self-heals the first time it is opened post-upgrade.
/// This costs one `stat` per path per call — no `chmod` subprocess when
/// the mode is already tight, which matters because gated mode calls
/// [openMemoryStore] on every single tool call (see the "Re-chmod'ing...
/// on every call" rejected alternative above for why an unconditional
/// chmod was rejected on cost).
///
/// `FileStat.statSync` on a path that does not exist yet reports
/// `FileSystemEntityType.notFound` with mode 0 (not looser than any
/// expected mode), so this is safe to call before the path is guaranteed
/// to exist. POSIX only — skipped on Windows, which has no POSIX mode
/// bits to compare.
void _tightenIfLoose(
  String path,
  String expectedOctal, {
  required LogSink log,
}) {
  if (Platform.isWindows) return;
  final stat = FileStat.statSync(path);
  if (stat.type == FileSystemEntityType.notFound) return;
  final currentMode = stat.mode & 0x1FF;
  const looseBits = 0x3F; // 0o077: any group or other permission bit.
  if (currentMode & looseBits == 0) return;
  log(
    '[perms] tightening pre-existing $path from '
    '0${currentMode.toRadixString(8)} to $expectedOctal',
  );
  tightenPermissions(path, expectedOctal, log: log);
}

/// Ensures the ObjectBox C library is loadable in standalone deployments.
///
/// The objectbox-dart bindings resolve `lib/libobjectbox.dylib` relative to
/// the *current working directory* (see objectbox-dart
/// `lib/src/native/bindings/bindings.dart`, `_tryObjectBoxLibFile`), with
/// `/usr/local/lib` as the only macOS fallback. A compiled binary launched
/// from an arbitrary cwd (as MCP clients do) would therefore fail to find
/// the library shipped next to it.
///
/// Fix: pre-load the dylib from a path relative to the *executable* before
/// the first ObjectBox call. dlopen registers the image process-wide (its
/// install name is `@rpath/libobjectbox.dylib`), so the bindings' own
/// subsequent lookup resolves to the already-loaded library.
///
/// Every attempt is logged; nothing falls through silently (contract §8).
void ensureNativeLibraryLoaded({LogSink log = stderrLog}) {
  final libName =
      Platform.isMacOS
          ? 'libobjectbox.dylib'
          : Platform.isWindows
          ? 'objectbox.dll'
          : 'libobjectbox.so';
  final exeDir = p.dirname(Platform.resolvedExecutable);
  final candidates = <String>[
    // dist/ layout: exe in dist/bin, dylib in dist/lib.
    p.normalize(p.join(exeDir, '..', 'lib', libName)),
    // exe and lib/ side by side.
    p.join(exeDir, 'lib', libName),
  ];
  // dev layout: project root cwd (same path the bindings try themselves —
  // listed here so the log shows explicitly which one won).
  //
  // 2026-09-07, CLAUDE.md platform gotcha 3 / the 2026-09-02 store-gate
  // status note (internal): rebuilding dist/ (`rm -rf dist`) orphans a
  // gated server's
  // cwd — the launcher `cd`s into dist/, so the inode it cd'd into is gone
  // after the rebuild. Gated mode re-opens the store (and re-runs this
  // function) on every tool call, and `Directory.current` throws
  // PathNotFoundException once the cwd is gone, killing every call of
  // every already-running server. The cwd-relative candidate is a dev-only
  // convenience anyway — production uses the launcher's dist/bin cwd, which
  // makes the exe-relative candidates above the ones that actually matter —
  // so skip it and log, instead of letting the whole function throw.
  try {
    candidates.add(p.join(Directory.current.path, 'lib', libName));
  } on FileSystemException catch (err) {
    log(
      '[store] cwd is gone (${err.message}) — skipping the cwd-relative '
      'dylib candidate; exe-relative candidates still apply',
    );
  }
  for (final candidate in candidates) {
    if (!File(candidate).existsSync()) continue;
    try {
      DynamicLibrary.open(candidate);
      log('[store] ObjectBox C library pre-loaded from $candidate');
      return;
    } catch (err) {
      log('[store] WARN: found but failed to load $candidate: $err');
    }
  }
  log(
    '[store] ObjectBox C library not found next to the executable or in '
    '<cwd>/lib — relying on the bindings\' default lookup '
    '(/usr/local/lib on macOS). Candidates tried: $candidates',
  );
}

/// Opens THE store for this process. Call exactly once from the entrypoint
/// (or per-test with a temp dir).
///
/// Uses the generated [openStore] helper so the model definition always
/// matches the committed objectbox-model.json.
///
/// R2-6 (the 2026-07-06 engineering log (internal), fix round 2) asked for
/// an actionable hint on a second process hitting the same [directory].
/// VERIFIED BY HAND
/// instead of assumed (contract: do not guess at ObjectBox behavior): two
/// independent OS processes opening the SAME store directory concurrently
/// with this project's objectbox 5.3.2 native library do NOT collide at
/// `openStore()` at all — both open successfully. The real, verified risk is
/// that two concurrent WRITERS silently interleave writes with PARTIAL DATA
/// LOSS (a hand probe had two processes each write 85 distinct rows; only
/// 103 of the expected 170 survived — no exception, no warning, just fewer
/// rows than written).
///
/// That risk is now handled one layer up, not inside this function:
/// [StoreInstanceGuard] (lib/src/instance_guard.dart) is acquired in
/// bin/remembox.dart BEFORE this function runs. Default mode tolerates a
/// second process (shared lock; write tools warn via `peersPresent()`).
/// `OBX_MEMORY_EXCLUSIVE=true` refuses to start if another instance is
/// already attached. See the 2026-07-06 engineering log (internal)'s
/// 2026-07-07 "R2-6 Follow-up" section and test/instance_guard_test.dart.
Store openMemoryStore(String directory, {LogSink log = stderrLog}) {
  ensureNativeLibraryLoaded(log: log);
  final dir = Directory(directory);
  if (!dir.existsSync()) {
    dir.createSync(recursive: true);
    log('[store] created store directory $directory');
    // M-2: only right after WE created it — see [tightenPermissions]'s doc
    // for why redundant chmods across the three creation sites are safe but
    // unnecessary.
    tightenPermissions(directory, '700', log: log);
  } else {
    // M-2 upgrade-path follow-up: a pre-existing directory may predate
    // this project's chmod-on-creation behavior — stat it and tighten
    // only if it is actually loose. See [_tightenIfLoose]'s doc.
    _tightenIfLoose(directory, '700', log: log);
  }
  // M-2: data.mdb/lock.mdb are created by openStore() below (the ObjectBox
  // C library), not by this Dart code, so "first open" is detected by
  // checking existence BEFORE calling openStore — chmod once, right after
  // the C library creates them, not on every subsequent open (gated mode
  // reopens this store on every tool call; re-chmod'ing already-600 files
  // on every call would be pure overhead).
  final dataMdb = p.join(directory, 'data.mdb');
  final lockMdb = p.join(directory, 'lock.mdb');
  final isFirstOpen = !File(dataMdb).existsSync();
  final store = openStore(directory: directory);
  log('[store] opened ObjectBox store at $directory');
  if (isFirstOpen) {
    // Just created by the C library above with the process umask's
    // default (typically loose) permissions — chmod unconditionally, no
    // need to stat first.
    tightenPermissions(dataMdb, '600', log: log);
    tightenPermissions(lockMdb, '600', log: log);
  } else {
    // M-2 upgrade-path follow-up: pre-existing files from before this
    // process's involvement — stat, tighten only if loose.
    _tightenIfLoose(dataMdb, '600', log: log);
    _tightenIfLoose(lockMdb, '600', log: log);
  }
  return store;
}

/// URL used to activate local writes when no real sync server is
/// configured: TCP port 0 is reserved (the kernel never assigns it to a
/// listener), so a client pointed here can never connect or replicate.
///
/// Why it exists at all: with the Sync-enabled C library, ObjectBox
/// REFUSES writes to `@Sync()` entity types until a sync client exists for
/// the store ("Can not modify object of sync-enabled type ... because sync
/// has not been activated for this store", OBX_ERROR 10001 — verified by
/// test/sync_annotation_test.dart). This is a DOCUMENTED DEVIATION from
/// contract §9's "do not create a sync client when sync is disabled": the
/// client below IS started (see `client.start()` below – merely
/// constructing it is not enough), but on this reserved port it never
/// connects and never replicates; its only effect is activating writes
/// for the `@Sync()` entity types. The alternative — shipping the
/// non-sync C library for local-only mode — would make sync support
/// impossible in the same binary.
const String localActivationSyncUrl = 'ws://127.0.0.1:0';

/// Creates the Sync client for this process (always exactly one):
///
/// - [MemoryConfig.syncUrl] set: a real client, started, with connection/
///   login events logged.
/// - unset (local-only default): a client that IS started on
///   [localActivationSyncUrl] but, on that reserved port, never connects
///   or replicates – it only activates local writes for the `@Sync()`
///   entity types – see the constant's docs.
///
/// The returned client must be closed BEFORE the store (objectbox-dart
/// docs: closing the store with a live sync client is undefined behavior).
/// Constructs a [SyncClient], translating the cryptic OBX 10098 ("Could not
/// create lws context") into an actionable error. Known cause: libwebsockets
/// cannot allocate its context when RLIMIT_NOFILE is *unlimited* — which is
/// exactly how Node-based MCP clients (Claude Code) spawn their children.
/// Reproduced 2026-07-07: `ulimit -n unlimited` → 10098, 10M fds → fine
/// (see the 2026-07-06 engineering log (internal), section on OBX 10098).
/// The dist launcher caps `ulimit -n` for this reason; this hint covers
/// anyone invoking the raw binary directly.
SyncClient _createSyncClient(
  Store store,
  List<String> urls,
  List<SyncCredentials> credentials,
) {
  try {
    return SyncClient(store, urls, credentials);
  } on StorageException catch (e) {
    if (e.errorCode == 10098 || e.message.contains('lws context')) {
      throw StateError(
        'ObjectBox Sync client could not initialize (OBX 10098, "Could not '
        'create lws context"). Known cause: this process was spawned with '
        'an UNLIMITED file-descriptor limit (typical for Node-based MCP '
        'clients such as Claude Code), which libwebsockets cannot handle. '
        'Launch RememBox via the dist/remembox launcher script (it caps '
        '`ulimit -n`), or cap the limit yourself before starting, e.g. '
        '`ulimit -n 1048576`. Original error: $e',
      );
    }
    rethrow;
  }
}

/// Fails loudly (contract §8) if the loaded ObjectBox C library has no Sync
/// support. Shared by [startSyncClient] and [startLocalActivationSyncClient]
/// so the check lives in exactly one place (no duplicated logic).
void _requireSyncCapableLibrary() {
  if (!Sync.isAvailable()) {
    throw StateError(
      'The loaded ObjectBox C library has no Sync support, which RememBox '
      'requires (its entities are sync-enabled). Re-run tool/setup.sh '
      '(it installs the Sync variant via install.sh --sync).',
    );
  }
}

/// Starts a sync client on [localActivationSyncUrl] purely to activate
/// writes for sync-enabled entity types (see the constant's docs) — used
/// whenever [MemoryConfig.syncUrl] is empty (persistent mode's default
/// local-only startup) AND, directly, by gated mode's [StoreGate] on EVERY
/// `withStore` open (F6, the 2026-09-01 store-gate engineering log (internal)).
///
/// [quiet] (2026-09-01, plan §14 MAJOR-1) suppresses this function's own
/// multi-line stderr logging: gated mode pays this cost on every single
/// tool call, so persistent mode's one-time verbose startup logging would
/// flood the operator's log if repeated per-call. [StoreGate] logs its own
/// single `[gate] <op> sync-client started (local, quiet)` line instead
/// when [quiet] is true. Persistent-mode callers (the default, unchanged
/// behavior) keep `quiet: false`.
SyncClient startLocalActivationSyncClient(
  Store store, {
  LogSink log = stderrLog,
  bool quiet = false,
}) {
  _requireSyncCapableLibrary();
  final client = _createSyncClient(
    store,
    [localActivationSyncUrl],
    [SyncCredentials.none()],
  );
  // start() is required — merely constructing the client does not
  // activate sync (verified by test/sync_annotation_test.dart). With the
  // reserved port the client stays permanently disconnected and never
  // replicates anything.
  client.start();
  if (quiet) return client;
  log(
    '[sync] OBX_MEMORY_SYNC_URL not set — local-only mode. Started a '
    'sync client on $localActivationSyncUrl (reserved port, can never '
    'connect) purely to activate writes for sync-enabled entity types '
    '(ObjectBox requires this with the Sync library); nothing is '
    'replicated.',
  );
  // FIX-6 (NIT, the 2026-07-06 engineering log (internal), review round 1,
  // finding 5): this client will repeatedly retry the reserved port and
  // print native
  // "LWS: Connect failed errno=49" / "Connection mismatch on destroy"
  // chatter straight to stderr — checked the Dart binding (objectbox
  // 5.3.2 in ~/.pub-cache: lib/src/native/store.dart's `debugFlags` only
  // exposes DebugFlags.log{TransactionsRead,TransactionsWrite,Queries,...}
  // — opt-in EXTRA logging, nothing that suppresses this) and it exposes
  // no log-level/verbosity control for the native sync client's own
  // stderr output. Documented as expected/harmless rather than built
  // around: this only fires in local-only mode (never for a real,
  // connected OBX_MEMORY_SYNC_URL, where connection logs matter).
  log(
    '[sync] note: local-only mode may print native "LWS: Connect failed" '
    '/ "Connection mismatch on destroy" lines to stderr — that is the '
    'reserved-port client above retrying a connection that can never '
    'succeed by design. Expected and harmless; it does not affect stdout '
    '(the MCP channel) or any tool result.',
  );
  return client;
}

/// Loopback hostnames dart:io/objectbox's URL handling treats as "this
/// machine" — L-2's non-loopback check below is host-string based (no DNS
/// resolution: resolving a hostname to decide trust would itself be a
/// network call driven by config, and could resolve differently over time),
/// so it recognizes only these literal forms.
const Set<String> _loopbackHosts = {'localhost', '127.0.0.1', '::1'};

/// SEC (L-2, 2026-09-07 security review): warns loudly (never silently) when
/// [config.syncUrl] combines EITHER condition an operator is unlikely to
/// intend: (a) plaintext `ws://` to a host this process cannot verify is
/// itself (not `localhost`/`127.0.0.1`/`::1`) — memory content and the
/// shared secret, if any, cross the network unencrypted; (b) an empty
/// [MemoryConfig.syncCredentials] — anyone who can reach the sync URL can
/// read/write this store's entire memory corpus, no authentication at all.
/// Each condition is named explicitly (contract §8: no silent
/// footguns) rather than folded into one vague warning. Deliberately does
/// NOT refuse to start — `ws://` + empty credentials is the documented,
/// intentional default for a same-machine sync server (see this file's
/// [localActivationSyncUrl] and README's trial/localhost trust model); this
/// is an observability guard for the case an operator pointed it at
/// something else without realizing the implications.
///
/// Deliberately a standalone top-level function (not `_`-prefixed, not a
/// [SyncClient]/[Store] method) so it is independently unit-testable with a
/// fake syncUrl/credentials pair and a log-capturing [LogSink] — see
/// test/store_config_test.dart's "L-2" group — WITHOUT constructing a real
/// [SyncClient] or attempting any network connection.
void warnIfSyncInsecure(
  String syncUrl,
  String syncCredentials,
  LogSink log,
) {
  final uri = Uri.tryParse(syncUrl);
  final isPlaintext = uri?.scheme == 'ws';
  final isNonLoopback = uri != null && !_loopbackHosts.contains(uri.host);
  final hasNoCredentials = syncCredentials.isEmpty;
  if (isPlaintext && isNonLoopback) {
    log(
      '[sync] WARN: OBX_MEMORY_SYNC_URL ("$syncUrl") is plaintext ws:// to '
      'a non-loopback host ("${uri.host}") — memory content'
      '${hasNoCredentials ? ' AND the (absent) credentials' : ' and the '
          'shared secret'} cross the network unencrypted and readable by '
      'anyone on the path. Use wss:// (TLS) unless this really is a '
      'same-machine sync server.',
    );
  }
  if (hasNoCredentials) {
    log(
      '[sync] WARN: OBX_MEMORY_SYNC_CREDENTIALS is empty for '
      'OBX_MEMORY_SYNC_URL ("$syncUrl") — this sync server accepts '
      'unauthenticated connections; anyone who can reach it can read/write '
      'this store\'s entire memory corpus. Set OBX_MEMORY_SYNC_CREDENTIALS '
      'unless this is a deliberately trusted localhost/trial setup.',
    );
  }
}

/// SEC (S3, 2026-09-08 pre-publication audit): warns loudly (never
/// silently) when [ollamaUrl] points anywhere other than this machine.
/// Every `remember()` text and every `recall()` query is POSTed to this
/// URL (see [OllamaEmbedder]) — unlike [warnIfSyncInsecure]'s sync URL,
/// there is no credentials/auth concept here at all, so a non-loopback
/// host means the entire memory corpus leaves the machine on every call,
/// contradicting the README's "what goes to the cloud" boundary unless the
/// operator did this deliberately. Warned unconditionally for ANY
/// non-loopback host (even `https://`/TLS) — because the risk here is the
/// export itself, not just network eavesdropping — with a second,
/// additional warning when the connection is also plaintext `http://` to
/// that non-loopback host (the network-sniffing risk on top of the export
/// risk). Deliberately does NOT refuse to start, same rationale as
/// [warnIfSyncInsecure]: this is an observability guard, not a policy
/// enforcement point.
///
/// Standalone top-level function for the same reason as
/// [warnIfSyncInsecure]: independently unit-testable with a fake
/// [ollamaUrl] and a log-capturing [LogSink] — see
/// test/store_config_test.dart's "warnIfOllamaRemote" group — WITHOUT
/// constructing a real [OllamaEmbedder] or attempting any network
/// connection.
void warnIfOllamaRemote(String ollamaUrl, LogSink log) {
  final uri = Uri.tryParse(ollamaUrl);
  final isNonLoopback = uri != null && !_loopbackHosts.contains(uri.host);
  if (!isNonLoopback) return;
  final isPlaintext = uri.scheme == 'http';
  log(
    '[embed] WARN: OBX_MEMORY_OLLAMA_URL ("$ollamaUrl") is a non-loopback '
    'host ("${uri.host}") — memory text and queries are sent to this URL '
    'on every remember/recall call. Use a local Ollama instance unless '
    'this is deliberate.',
  );
  if (isPlaintext) {
    log(
      '[embed] WARN: OBX_MEMORY_OLLAMA_URL ("$ollamaUrl") is also '
      'plaintext http:// to that non-loopback host — memory text and '
      'queries cross the network unencrypted and readable by anyone on '
      'the path. Use https:// (TLS) unless this really is a same-machine '
      'setup.',
    );
  }
}

SyncClient startSyncClient(
  Store store,
  MemoryConfig config, {
  LogSink log = stderrLog,
}) {
  _requireSyncCapableLibrary();
  if (config.syncUrl.isEmpty) {
    return startLocalActivationSyncClient(store, log: log);
  }
  warnIfSyncInsecure(config.syncUrl, config.syncCredentials, log);
  final credentials =
      config.syncCredentials.isEmpty
          ? SyncCredentials.none()
          : SyncCredentials.sharedSecretString(config.syncCredentials);
  final client = _createSyncClient(store, [config.syncUrl], [credentials]);
  client.connectionEvents.listen(
    (event) => log('[sync] connection event: ${event.name}'),
  );
  client.loginEvents.listen(
    (event) => log('[sync] login event: ${event.name}'),
  );
  client.start();
  log(
    '[sync] sync client started against ${config.syncUrl} '
    '(auth: ${config.syncCredentials.isEmpty ? 'none/localhost' : 'shared secret'})',
  );
  return client;
}
